PPTP-1519 Added tests
hmrc/plastic-packaging-tax-registration pull request #109
Opened 2021-12-06 16:21 UTC by kiranprakashdigital

### Description of Work carried through

Brief description of what/why/how.

#### Check list 
 - [ ] `./precheck` was executed (Integration/Component/Unit tests)
 - [ ] `sbt scalafmt test:scalafmt` was executed

2021-12-07 07:06 UTC, RyanKellyHMRC approved these changes

2021-12-07 10:31 UTC, tmc-ee approved these changes

2021-12-07 13:46 UTC, RyanKellyHMRC requested changes
I think we need to use a fully populated subscription in the test(s).

2021-12-07 13:46 UTC, RyanKellyHMRC commented on test/uk/gov/hmrc/plasticpackagingtaxregistration/base/data/RegistrationTestData.scala
> +  protected val ukLimitedCompany: Subscription = Subscription(
It's probably worth making it clear that this is a subscription, `ukLimitedCompanySubscription`?

2021-12-07 13:46 UTC, RyanKellyHMRC commented on test/uk/gov/hmrc/plasticpackagingtaxregistration/base/data/RegistrationTestData.scala
> +  )
Unless it's being tested elsewhere, I think this subscription should be fully loaded with every possible field populated, including group details.

2021-12-09 09:03 UTC, RyanKellyHMRC requested changes
A few minor bits Kiran, cheers.

2021-12-09 09:03 UTC, RyanKellyHMRC commented on test/uk/gov/hmrc/plasticpackagingtaxregistration/models/RegistrationSpec.scala
> +                                                "01"
Very minor but I think it would be better to use one of the expected values here, from the enum.

2021-12-09 09:34 UTC, kiranprakashdigital commented on app/uk/gov/hmrc/plasticpackagingtaxregistration/controllers/SubscriptionController.scala
> +        println(Json.toJson(request.body))
Oops, yeah removed it

2021-12-09 09:34 UTC, kiranprakashdigital commented on app/uk/gov/hmrc/plasticpackagingtaxregistration/models/PrimaryContactDetails.scala
> +        s"${individualDetails.firstName} ${individualDetails.middleName} ${individualDetails.lastName}"
Fixed

2021-12-09 09:34 UTC, kiranprakashdigital commented on test/uk/gov/hmrc/plasticpackagingtaxregistration/models/RegistrationSpec.scala
> +                                                "01"
I have created the enum now.

2021-12-09 09:48 UTC, RyanKellyHMRC requested changes
We need to use the enum values from the api spec for ChangeOfCircumstances.

2021-12-09 09:48 UTC, RyanKellyHMRC commented on app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/ChangeOfCircumstanceDetails.scala
> +}
Sorry Kiran, I didn't mean that. I meant use the enum value from the api spec: "Update to details" or "Manual to Online" in your test. We could continue to use this enum but the values need to be these strings.

2021-12-09 09:53 UTC, kiranprakashdigital commented on app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/ChangeOfCircumstanceDetails.scala
> +}
I think I got confused seeing the api spec as it has 01  and 03 before the values in description.

2021-12-09 09:54 UTC, RyanKellyHMRC approved these changes
Thanks for the changes Kiran.

2021-12-09 09:56 UTC, merged