Failing test to show OrgType / PartnerType mismatch on Subscrition.le…
hmrc/plastic-packaging-tax-registration pull request #134
Opened 2022-02-10 10:09 UTC by tonymccrae-ee

…gelEntityDetails.customerDetails.organisationDetails.organisationType.

### Description of Work carried through

Brief description of what/why/how.

#### Check list 
 - [ ] `./precheck` was executed (Integration/Component/Unit tests)
 - [ ] `sbt scalafmt test:scalafmt` was executed
 - [ ] Required Environment Config has been amended/added
 - [ ] Links to dependencies have been included (BE/FE work)
 - [ ] User Acceptance Tests (UAT) were run locally and have passed.

2022-02-11 16:04 UTC, tonymccrae-ee commented on app/uk/gov/hmrc/plasticpackagingtaxregistration/models/Registration.scala
> +        /*
This is the LLP / Group fix - I can't figure this bit out.

2022-02-14 12:41 UTC, RyanKellyHMRC requested changes
Man, I bet that was pretty tedious to pull together! I think we should be able to populate the partnership name - see comment.

Also, I wondered whether we ought to have some additional tests here since this code is so complicated?

2022-02-14 12:41 UTC, RyanKellyHMRC commented on test/uk/gov/hmrc/plasticpackagingtaxregistration/models/RegistrationSpec.scala
> +
Is there a reason for all this additional checking (below) or could we just use `assertConversion` as other tests do? I made some changes so that json was dumped during the running of the above commented out test and, whilst the rehydrated registration differed from the initial one, the subscription subsequently created from it was identical.

Also, since this conversion is pretty complicated, I wonder whether we ought to have some additional tests with different partnership registrations.

2022-02-14 12:50 UTC, RyanKellyHMRC commented on app/uk/gov/hmrc/plasticpackagingtaxregistration/models/Registration.scala
> +                partnershipName = None, // Does not appear to be persisted on subscription
I wonder whether we might fail (as a result of this) if we have captured a non-incorp partner (eg. Scottish Partnership)?

2022-02-14 13:53 UTC, RyanKellyHMRC commented on app/uk/gov/hmrc/plasticpackagingtaxregistration/models/Registration.scala
> +                partnershipName = None, // Does not appear to be persisted on subscription
I have added a test which includes a Scottish Partnership partner and everything works fine. Having looked into this it appears that we are always creating a CompanyProfile when rehydrating partners in a Registration. This might cause the partnership name to be lost if the user attempts to modify (post registration) a non-incorp partner.  I think we could circumvent this by ensuring that the partner name is set here.

2022-02-14 14:28 UTC, tonymccrae-ee commented on test/uk/gov/hmrc/plasticpackagingtaxregistration/models/RegistrationSpec.scala
> +
assertConversion will not work because it's expecting a perfect 1 to 1 mapping; that's not possible because we can't get all of the field back from the Subscription (ie. partner.id for example).

2022-02-14 15:45 UTC, RyanKellyHMRC commented on test/uk/gov/hmrc/plasticpackagingtaxregistration/models/RegistrationSpec.scala
> +
The full conversion (reg -> sub -> reg -> sub) does actually work and produces a subscription which is identical to that initially created. I do agree that the rehydrated reg is not "equal" to that with which we start though for the reasons pointed out by Tony.

Since Tony is keen that this additional verification code is useful and might help future readers I'm happy for it to remain.

2022-02-15 09:58 UTC, merged