PPTP-993 : General Partnership GRS Integration
hmrc/plastic-packaging-tax-registration pull request #40
Opened 2021-07-21 16:22 UTC by RyanKellyHMRC

2021-07-22 10:25 UTC, tmc-ee requested changes

2021-07-22 10:25 UTC, tmc-ee commented on test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/CustomerDetailsSpec.scala
Can we add a test for exceptions? e.g. `incorporation details are missing from the partnership`

2021-07-22 10:25 UTC, tmc-ee commented on test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/LegalEntityDetailsSpec.scala
>      "throw an exception" when {
Can we add a test for exceptions? e.g. `incorporation details are missing from the partnership`

Also, I know this isn't part of the partnerships work per se, but do we also need to add test coverage for `organisation type is 'None'` here, i.e. replicating https://github.com/hmrc/plastic-packaging-tax-registration/blob/c746c2e2691ec878c45d8a6d7cd4571bdd6791b4/test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/CustomerDetailsSpec.scala#L68

2021-07-22 10:41 UTC, RyanKellyHMRC commented on test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/CustomerDetailsSpec.scala
Additional test added.

2021-07-22 10:41 UTC, RyanKellyHMRC commented on test/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/LegalEntityDetailsSpec.scala
>      "throw an exception" when {
Additional tests added.

2021-07-22 16:59 UTC, tmc-ee approved these changes
Thanks for the changes, tests looking good! 👍

2021-07-23 13:56 UTC, PauloPortugal commented on app/uk/gov/hmrc/plasticpackagingtaxregistration/connectors/models/eis/subscription/LegalEntityDetails.scala
> +                             customerIdentification2 = Some(details.postcode),
:+1:

2021-07-23 13:56 UTC, PauloPortugal approved these changes

2021-07-26 12:57 UTC, kiranprakashdigital approved these changes

2021-07-26 14:49 UTC, merged